### ISSUE TITLE
解除关联关系

### ISSUE THREAD

**Issue by LaughingZhu** [CatchingFireStage/fruits-web#3]
spu解除关联关系，无法解除指定id关系 @FlashFeiFei

**Comment by FlashFeiFei** [comment]
specificationSpuId 作为唯一标识，需要&nbsp;specificationSpuId的值，不是 id 的值




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月6日(星期三) 下午3:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: [CatchingFireStage/fruits-web] 解除关联关系 (#3)





 
spu解除关联关系，无法解除指定id关系 @FlashFeiFei
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
